dist: trusty
sudo: required

services:
- docker

language: go

go:
- "1.10.1"

before_script:
- scripts/terraform_install.sh

script:
- cd $HOME/gopath/src/github.com/imjoey/terraform-provider-ovirt && make test

branches:
  only:
  - master

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
